#!/bin/bash
set -e

if [ "$1" = "configure" ]; then
    xdg-desktop-menu install --mode system /usr/share/turtlebot-desktop/*.desktop
    update-desktop-database
    glib-compile-schemas /usr/share/glib-2.0/schemas
#        xdg-desktop-icon install /usr/share/turtlebot-desktop/turtlebot*.desktop
#        xdg-mime install --mode system /usr/share/turtlebot-desktop/ros-roslaunch.xml
#        xdg-mime default ros-roslaunch.desktop application/x-ros-launch
fi
#DEBHELPER#
